Repository dynamicCat/CITS5505-Group-60-project, pull requests merged in 2025-05, with the labels that each got.

#9 (feat: introductory) synchronise names in the navbar
  app/templates/home.html
Labels: enhancement

#12 Set up a database that meets the usage requirements and a project backend folder
  app/__init__.py
  app/auth/__init__.py
  app/auth/forms.py
  app/auth/routes.py
  app/errors/__init__.py
  app/errors/handlers.py
  app/main/__init__.py
  app/main/forms.py
  app/main/routes.py
  app/models.py
  app/static/images/faces.png
  config.py
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/e2d75e820dec_initial_migration.py
  requirements.txt
  run.py
Labels: enhancement

#14 Delete and modify front-end code, and implement the specific function
  README.md
  app/auth/forms.py
  app/auth/routes.py
  app/main/forms.py
  app/main/routes.py
  app/routes.py
  app/static/css/share.css
  app/static/css/style.css
  app/static/css/upload.css
  app/static/css/visualise.css
  app/static/js/share.js
  app/static/js/template.js
  app/static/js/visualise.js
  app/templates/auth/login.html
  app/templates/auth/register.html
  app/templates/base.html
  app/templates/errors/404.html
  app/templates/errors/500.html
  app/templates/home.html
  app/templates/main/home.html
  app/templates/main/preview_upload.html
  app/templates/main/upload.html
  app/templates/main/view_stats.html
  app/templates/share.html
  app/templates/upload.html
  app/templates/visualise.html
  requirements.txt
Labels: enhancement

#15 Implement the function of receive results.
  app/main/routes.py
  app/templates/base.html
  app/templates/main/home.html
  app/templates/main/received_results.html
Labels: enhancement

#16 Add the front end of the share interface
  README.md
  app/main/forms.py
  app/static/js/share.js
  app/static/js/share_users.js
  app/templates/base.html
  app/templates/main/home.html
  app/templates/main/share.html
  app/templates/main/view_stats.html
Labels: enhancement

#20 Vinh introductory
  app/main/routes.py
  app/static/css/style.css
  app/templates/base.html
  app/templates/errors/404.html
  app/templates/main/home.html
Labels: bug, enhancement

#22 Remove the public share feature from the system
  README.md
  app/main/routes.py
  app/static/css/style.css
  app/static/js/share.js
  app/templates/base.html
  app/templates/main/received_results.html
  app/templates/main/share.html
  app/templates/main/view_stats.html
  sample_matches.csv
Labels: help wanted, invalid

#26 Added player usage logic to the system
  app/main/forms.py
  app/main/routes.py
  app/models.py
  app/static/css/style.css
  app/templates/base.html
  app/templates/main/players.html
  app/templates/main/share.html
  app/templates/main/view_stats.html
  migrations/versions/160ea8a1f877_add_model_matchcalendar.py
  migrations/versions/6a3999cd2c66_add_player_table_adjust_matchresult.py
Labels: bug, enhancement

#27 Fixed bugs and added more charts to the data analysis interface
  README.md
  app/main/routes.py
  app/templates/main/view_stats.html
  demo_matchs.csv
  requirements.txt
Labels: bug, documentation, enhancement

#28 Fixed the bugs and add SocketIO
  README.md
  app/__init__.py
  app/main/forms.py
  app/main/routes.py
  app/templates/base.html
  app/templates/main/received_results.html
  app/templates/main/share.html
  app/templates/main/view_stats.html
  requirements.txt
  run.py
Labels: bug, documentation, enhancement

#34 feat(selenium_webdriver_test): add Selenium integration tests for UI, auth, routing, and responsiveness
  app/auth/routes.py
  app/templates/base.html
  requirements.txt
  run.py
  tests/__init__.py
  tests/test_selenium.py
Labels: enhancement, test integration

#38 Unit test on test_forms.py
  app/models.py
  tests/test_forms.py
Labels: enhancement

#40 Vinh/UI improvements: UI Enhancements, Calendar Feature, Test Refactor, and Documentation Updates
  README.md
  app/main/routes.py
  app/models.py
  app/static/css/home-style.css
  app/static/css/style.css
  app/static/js/home.js
  app/templates/base.html
  app/templates/main/home.html
  app/templates/main/players.html
  app/templates/main/upload.html
  demo_matchs.csv
  tests/test_selenium.py
Labels: enhancement

#46 Modify the upload csv function
  app/main/routes.py
Labels: enhancement

#51 Comments added for unit tests
  tests/test_forms.py
  tests/test_init.py
  tests/test_models.py
Labels: documentation, question

#53 fix(share): always enable share button, add alerts for no selection
  app/static/js/share.js
  app/templates/main/share.html
Labels: fix-issues

#56 Added the ability to batch upload players via csv.
  app/main/forms.py
  app/main/routes.py
  app/templates/main/players.html
  app/templates/main/received_results.html
  demo_players.csv
Labels: documentation, enhancement

#57 fix problem of user experience in share view
  app/static/js/share.js
Labels: bug, fix-issues

#58 fix the selenium test for front-end
  tests/test_selenium.py
Labels: bug, test-integration

#59 fix the register error
  app/auth/routes.py
  app/templates/auth/register.html
Labels: bug
